export enum EmployeeDocumentType {
  IDENTITY = 'IDENTITY',
  PASSPORT = 'PASSPORT',
  WORK_PERMIT = 'WORK_PERMIT',
  VISA = 'VISA',
  EDUCATION = 'EDUCATION',
  CERTIFICATION = 'CERTIFICATION',
  MEDICAL = 'MEDICAL',
  OTHER = 'OTHER',
}
