export enum ImportRowErrorMode {
  CONTINUE_ON_ROW_ERROR = 'CONTINUE_ON_ROW_ERROR',
  STOP_ON_ROW_ERROR = 'STOP_ON_ROW_ERROR',
  STOP_ON_ERROR_THRESHOLD = 'STOP_ON_ERROR_THRESHOLD',
  ALL_OR_NOTHING = 'ALL_OR_NOTHING',
}
