export enum OnboardingRequirementType {
  PERSONAL_INFORMATION = 'PERSONAL_INFORMATION',
  DOCUMENT = 'DOCUMENT',
  BANK_ACCOUNT = 'BANK_ACCOUNT',
  TAX_INFORMATION = 'TAX_INFORMATION',
  CONTRACT = 'CONTRACT',
  POLICY_ACKNOWLEDGEMENT = 'POLICY_ACKNOWLEDGEMENT',
  OTHER = 'OTHER',
}
